matrix:
  include:
    - os: osx
      sudo: required
      language: c
      language: cpp
      language: node_js
      compiler: clang
      node_js: 4.2.3
      osx_image: xcode7.3
      # language: python  # does not work on travis osx, so we install with brew...

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache/fpm

before_install:
  - brew install gnu-tar dpkg libicns graphicsmagick lzip python
install:
  - npm install npm -g
  - npm install
  - npm prune
  - pip install -q --upgrade setuptools pip
  - pip install -q jupyter
  - pip install -q numpy matplotlib plotly toyplot ipywidgets==4.1.1 pandas
script:
  - npm run test
  - npm run dist:all
addons:
  artifacts:
    # set ARTIFACTS_KEY=(AWS access key id) ARTIFACTS_SECRET=(AWS secret access key) ARTIFACTS_BUCKET=(S3 bucket name)
    paths:
      - $(git ls-files -o | tr "\n" ":")
    debug: true
    s3_region: "us-west-1" # defaults to "us-east-1"
