language: cpp
compiler: clang
osx_image: xcode7.3
sudo: required
dist: trusty
language: c
language: node_js
node_js:
  - '4.2.3'
matrix:
  include:
    - os: osx

branches:
  only:
    - travis
cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache/fpm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar dpkg libicns graphicsmagick lzip; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$NODE_VERSION" == "4" ]]; then npm install npm -g ; fi
  - npm install
  - npm prune
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm run test
